spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitystudy?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  session:
    store-type: none

server:
  port: 8060

security:
  basic:
    enabled: true
